"""Module 1: Playwright-based anti-bot bootstrapper.

Launches a real (headless) Chromium browser to let Akamai Bot Manager
(Coles) and Imperva/Incapsula (Woolworths) run their client-side challenges
to completion, then harvests the resulting cookies and dynamic API
headers/tokens into a `SessionContext` that `hybrid_scraper.engine` can reuse
over fast `curl_cffi` requests — without paying Playwright's overhead on
every subsequent call.

Cookie lifecycle (why a real browser is required at all):
  1. Akamai's `_abck` cookie exists from first page load, but its embedded
     sensor-state segment only flips from "unvalidated" to "validated" after
     the page's obfuscated sensor_data telemetry POST completes — that POST
     is generated by Akamai's own injected JS actually executing in a real
     browser context, which is exactly what curl_cffi (an HTTP client, not a
     JS runtime) cannot do on its own.
  2. Imperva/Incapsula cookies (`reese84`, `incap_ses_*`, `visid_incap_*`)
     simply do not exist until its client-side JS challenge has been solved;
     they are minted by the challenge script itself, not returned by a
     simple GET.
  3. Both retailers' front-ends also embed a rotating API key / bearer token
     into their bundled JS and attach it as a request header on every search
     XHR. The only reliable way to obtain a currently-valid value is to
     observe it on an outgoing request from the real page, which is why this
     module listens on `page.on("request", ...)` rather than trying to
     parse it out of a JS bundle.
"""

from __future__ import annotations

import asyncio
import logging
import time
from typing import Any, Dict, Optional, Set

from curl_cffi.requests import AsyncSession as CurlAsyncSession
from playwright.async_api import (
    Browser,
    BrowserContext,
    Playwright,
    Request,
    Response,
    TimeoutError as PlaywrightTimeoutError,
    async_playwright,
)

from hybrid_scraper.config import (
    DEFAULT_USER_AGENT,
    IMPERSONATE_TARGET,
    RETAILER_CONFIGS,
    STEALTH_INIT_SCRIPT,
)
from hybrid_scraper.exceptions import BootstrapError
from hybrid_scraper.models import RetailerName, SessionContext

logger = logging.getLogger(__name__)


class PlaywrightBootstrapper:
    """Owns the Playwright + Chromium lifecycle; use as an async context manager.

    Example:
        async with PlaywrightBootstrapper() as bootstrapper:
            store_id = await bootstrapper.resolve_store_id("Coles", "Chatswood NSW")
            session = await bootstrapper.bootstrap("Coles", store_id)
    """

    def __init__(
        self,
        headless: bool = True,
        navigation_timeout_ms: float = 45_000,
        challenge_wait_timeout_ms: float = 20_000,
    ) -> None:
        self._headless = headless
        self._navigation_timeout_ms = navigation_timeout_ms
        self._challenge_wait_timeout_ms = challenge_wait_timeout_ms
        self._playwright: Optional[Playwright] = None
        self._browser: Optional[Browser] = None

    async def __aenter__(self) -> "PlaywrightBootstrapper":
        logger.info("Launching Chromium headless=%s", self._headless)
        self._playwright = await async_playwright().start()
        try:
            self._browser = await self._playwright.chromium.launch(
                headless=self._headless,
                args=[
                    "--disable-blink-features=AutomationControlled",
                    "--disable-dev-shm-usage",
                    "--no-sandbox",
                ],
            )
        except Exception as exc:
            logger.error("Chromium launch failed: %s", exc, exc_info=True)
            await self._playwright.stop()
            self._playwright = None
            raise BootstrapError(f"Failed to launch Chromium: {exc}") from exc
        logger.info("Chromium launched successfully")
        return self

    async def __aexit__(self, *_exc_info: Any) -> None:
        if self._browser is not None:
            await self._browser.close()
            self._browser = None
        if self._playwright is not None:
            await self._playwright.stop()
            self._playwright = None
        logger.info("Chromium and Playwright shut down")

    async def _new_stealth_context(self) -> BrowserContext:
        if self._browser is None:
            raise BootstrapError("PlaywrightBootstrapper must be used as an async context manager")
        context = await self._browser.new_context(
            user_agent=DEFAULT_USER_AGENT,
            viewport={"width": 1920, "height": 1080},
            locale="en-AU",
            timezone_id="Australia/Sydney",
        )
        await context.add_init_script(STEALTH_INIT_SCRIPT)
        return context

    @staticmethod
    def _anti_bot_cookies_present(cookie_names: Set[str], retailer: RetailerName) -> bool:
        # Corrected via live capture: Coles is fronted by Imperva/Incapsula
        # (`visid_incap_*`, `incap_ses_*`) and Woolworths by Akamai Bot
        # Manager (`_abck`, `bm_sz`) — the reverse of this module's original
        # (unverified) assumption. Checking both sets per retailer rather
        # than hard-failing on vendor identity, in case that changes again.
        if retailer == "Coles":
            return any(name.startswith("incap_ses") or name.startswith("visid_incap") for name in cookie_names)
        return "_abck" in cookie_names or "bm_sz" in cookie_names

    @staticmethod
    async def _harvest_curl_cffi_cookies(retailer: RetailerName) -> Dict[str, str]:
        """GET the retailer's homepage via curl_cffi and return the cookies it sets.

        IMPORTANT (discovered via live testing): Incapsula/Akamai session
        cookies are bound to the exact client fingerprint that requested
        them. Cookies harvested from Playwright's real Chromium do NOT work
        when replayed through curl_cffi's Chrome-*impersonating* TLS stack
        — Coles' search API silently returned empty bodies when handed
        Playwright-sourced cookies, but worked immediately with cookies
        curl_cffi obtained for itself. So every `SessionContext` this module
        returns gets its cookies from curl_cffi directly, never from
        `context.cookies()` — Playwright's job is only to observe secrets
        that can't be gotten any other way (e.g. Coles' subscription key).
        """
        config = RETAILER_CONFIGS[retailer]
        async with CurlAsyncSession() as session:
            response = await session.get(config.base_url, impersonate=IMPERSONATE_TARGET, timeout=30)
            if response.status_code >= 400:
                raise BootstrapError(
                    f"curl_cffi cookie harvest failed for {retailer}: homepage returned {response.status_code}"
                )
            return dict(response.cookies)

    async def _curl_cffi_cookie_fallback(self, retailer: RetailerName, store_id: str) -> SessionContext:
        """Build a full curl_cffi-only SessionContext, bypassing Playwright's browser engine entirely.

        Used when Playwright's own browser engine gets network-blocked
        (observed for Woolworths from this environment: Chromium
        consistently gets a 403 "Access Denied" edge response on every
        navigation, while a plain curl_cffi GET with Chrome TLS
        impersonation succeeds immediately — i.e. the block fingerprints
        the real browser engine specifically, not the TLS handshake or
        declared User-Agent). Only safe for retailers that don't need a
        secret captured off a live browser request
        (`subscription_key_header is None`); Coles still requires the real
        bootstrap path for its APIM key.
        """
        logger.warning(
            "Playwright's browser engine appears network-blocked for retailer=%s — "
            "falling back to a curl_cffi-only cookie harvest",
            retailer,
        )
        config = RETAILER_CONFIGS[retailer]
        cookies = await self._harvest_curl_cffi_cookies(retailer)
        headers = {**config.default_headers, "User-Agent": DEFAULT_USER_AGENT}
        logger.info(
            "curl_cffi fallback bootstrap success retailer=%s store_id=%s cookies=%d",
            retailer,
            store_id,
            len(cookies),
        )
        return SessionContext(
            retailer=retailer,
            cookies=cookies,
            headers=headers,
            store_id=str(store_id),
            created_at=time.time(),
        )

    async def bootstrap(self, retailer: RetailerName, store_id: str) -> SessionContext:
        """Resolve the anti-bot challenge for `retailer`/`store_id` and return a SessionContext."""
        config = RETAILER_CONFIGS[retailer]
        logger.info("bootstrap start retailer=%s store_id=%s", retailer, store_id)
        start = time.monotonic()
        context = await self._new_stealth_context()
        captured_headers: Dict[str, str] = {}

        try:
            page = await context.new_page()
            page.set_default_navigation_timeout(self._navigation_timeout_ms)

            def _on_request(request: Request) -> None:
                if config.search_url not in request.url:
                    return
                headers = request.headers
                newly_captured = []
                for header_name in (config.subscription_key_header, "authorization", "ocp-apim-subscription-key"):
                    if header_name and header_name in headers and header_name not in captured_headers:
                        captured_headers[header_name] = headers[header_name]
                        newly_captured.append(header_name)
                if newly_captured:
                    # Log which header NAMES were captured, never the values —
                    # these are live session secrets and must not land in a log file.
                    logger.debug(
                        "Captured search-request headers retailer=%s names=%s", retailer, newly_captured
                    )

            page.on("request", _on_request)

            # Step 1: apply store selection *before* navigating. Both
            # retailers persist the chosen store as a cookie their own
            # front-end sets after a UI interaction; setting it directly
            # ahead of the first navigation is equivalent and avoids both
            # depending on exact store-picker DOM structure AND an extra
            # reload cycle (a reload here was observed, live, to sometimes
            # leave the page's search input non-interactive — likely a
            # hydration timing issue with the reloaded SPA shell).
            # NOTE: the cookie name below is unverified for Coles — its
            # real search API takes `storeId` as a query parameter instead
            # (see engine.py), so this cookie may not even be load-bearing;
            # kept as a best-effort in case the front-end also reads it.
            await context.add_cookies(
                [
                    {
                        "name": "selectedStoreId" if retailer == "Coles" else "swSelectedStore",
                        "value": str(store_id),
                        "url": config.base_url,
                    }
                ]
            )

            # Step 2: land on the site so the vendor's sensor/challenge JS runs at all.
            logger.debug("Navigating to homepage retailer=%s url=%s", retailer, config.base_url)
            try:
                nav_response = await page.goto(config.base_url, wait_until="domcontentloaded")
            except PlaywrightTimeoutError as exc:
                logger.error("Homepage navigation timed out retailer=%s store_id=%s", retailer, store_id)
                raise BootstrapError(f"Homepage navigation timed out for {retailer}") from exc

            if nav_response is not None and nav_response.status >= 400:
                logger.warning(
                    "Homepage navigation network-blocked retailer=%s status=%d",
                    retailer,
                    nav_response.status,
                )
                if config.subscription_key_header is None:
                    return await self._curl_cffi_cookie_fallback(retailer, store_id)
                raise BootstrapError(
                    f"{retailer} homepage returned {nav_response.status} and this retailer requires "
                    "a browser-captured subscription key, so the curl_cffi fallback isn't usable"
                )

            # Step 3: poll until the anti-bot vendor's cookies mature (see
            # module docstring for why this can't be short-circuited).
            deadline = time.monotonic() + (self._challenge_wait_timeout_ms / 1000)
            challenge_cleared = False
            while time.monotonic() < deadline:
                cookie_names = {c["name"] for c in await context.cookies()}
                if self._anti_bot_cookies_present(cookie_names, retailer):
                    challenge_cleared = True
                    break
                await asyncio.sleep(0.5)
            if challenge_cleared:
                logger.debug(
                    "Anti-bot cookies matured retailer=%s store_id=%s elapsed=%.1fs",
                    retailer,
                    store_id,
                    time.monotonic() - start,
                )
            else:
                logger.warning(
                    "Anti-bot cookies did not mature within timeout retailer=%s store_id=%s — "
                    "continuing anyway, downstream requests will likely 401/403",
                    retailer,
                    store_id,
                )

            # Step 4: trigger one genuine search so a real, fully-headered
            # XHR fires for the request listener above to observe.
            try:
                # Coles' search input is a plain <input type="text"> (id
                # confirmed via live capture), which get_by_role("searchbox")
                # does NOT match — that role requires type="search" or an
                # explicit role attribute. Fall back to role-based lookup
                # for other retailers where the real markup is unconfirmed.
                if retailer == "Coles":
                    search_input = page.locator("#search-text-input")
                else:
                    search_input = page.get_by_role("searchbox")
                await search_input.wait_for(state="visible", timeout=self._challenge_wait_timeout_ms)
                await search_input.fill("milk", timeout=self._challenge_wait_timeout_ms)
                await search_input.press("Enter", timeout=self._challenge_wait_timeout_ms)
                await page.wait_for_load_state("networkidle", timeout=self._challenge_wait_timeout_ms)
            except PlaywrightTimeoutError as exc:
                # Non-fatal: some page layouts don't expose role=searchbox;
                # captured_headers may already hold values from background
                # XHRs the SPA fires on its own during initial load.
                logger.debug(
                    "No searchbox interaction completed retailer=%s — relying on background XHRs for headers: %s",
                    retailer,
                    exc,
                )

            if not captured_headers and config.subscription_key_header:
                logger.error(
                    "No auth headers captured retailer=%s store_id=%s expected_header=%s",
                    retailer,
                    store_id,
                    config.subscription_key_header,
                )
                raise BootstrapError(
                    f"No {config.subscription_key_header!r} header observed on any outgoing "
                    f"{retailer} search request — page flow/selectors likely need updating"
                )

            # Cookies come from a fresh curl_cffi request, not context.cookies()
            # — see _harvest_curl_cffi_cookies' docstring for why Playwright's
            # own browser-session cookies don't work when replayed through
            # curl_cffi's separate TLS stack.
            cookies = await self._harvest_curl_cffi_cookies(retailer)
            headers = {**config.default_headers, **captured_headers, "User-Agent": DEFAULT_USER_AGENT}

            logger.info(
                "bootstrap success retailer=%s store_id=%s cookies=%d headers=%d elapsed=%.1fs",
                retailer,
                store_id,
                len(cookies),
                len(headers),
                time.monotonic() - start,
            )
            return SessionContext(
                retailer=retailer,
                cookies=cookies,
                headers=headers,
                store_id=str(store_id),
                created_at=time.time(),
            )
        except BootstrapError:
            raise
        except Exception as exc:
            logger.error(
                "Unexpected bootstrap failure retailer=%s store_id=%s: %s", retailer, store_id, exc, exc_info=True
            )
            raise BootstrapError(f"Bootstrap failed for {retailer} store {store_id}: {exc}") from exc
        finally:
            await context.close()
